In [2]:
import numpy as np

In [3]:
def computeloss(x,y):
        shifted_x = x - np.max(x,axis = 1, keepdims=True)

        exp_x = np.exp(shifted_x)

        denom = np.sum(exp_x,axis = 1, keepdims=True) 

        scores = exp_x/denom
        scores = scores + 1e-10 #epsilon to prevent -log(0)
        print("\n    scores   \n")
        print(scores)
        N = x.shape[0]
        print("scores (N,y)")
        print(scores[np.arange(N), y])
        print(y)
        loss = np.sum(-np.log(scores[np.arange(N), y]))/N

        dx = scores
        dx[np.arange(N), y] -= 1
        dx /= N
        return loss, dx

In [9]:
X=np.array([[1,4,6,3,1,7,4,9,3,5,4,5,7,3,5],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[15,14,13,12,10,3,5,0,6,3,6,3,7,7,8]])
Y=np.array([1,2,4])

In [10]:
computeloss(X,Y)



    scores   

[[2.38980307e-04 4.80004587e-03 3.54678075e-02 1.76583825e-03
  2.38980307e-04 9.64114966e-02 4.80004587e-03 7.12389956e-01
  1.76583825e-03 1.30478773e-02 4.80004587e-03 1.30478773e-02
  9.64114966e-02 1.76583825e-03 1.30478773e-02]
 [5.25726559e-07 1.42890112e-06 3.88398413e-06 1.05575917e-05
  2.86983378e-05 7.80099982e-05 2.12052989e-04 5.76419614e-04
  1.56687079e-03 4.25919623e-03 1.15776955e-02 3.14714392e-02
  8.55482411e-02 2.32544229e-01 6.32120752e-01]
 [6.40355113e-01 2.35573481e-01 8.66626407e-02 3.18814039e-02
  4.31467891e-03 3.93457780e-06 2.90721772e-05 1.95986115e-07
  7.90261991e-05 3.93457780e-06 7.90261991e-05 3.93457780e-06
  2.14815309e-04 2.14815309e-04 5.83928379e-04]]
scores (N,y)
[4.80004587e-03 3.88398413e-06 4.31467891e-03]
[1 2 4]


(7.747837089009706,
 array([[ 7.96601022e-05, -3.31733318e-01,  1.18226025e-02,
          5.88612751e-04,  7.96601022e-05,  3.21371655e-02,
          1.60001529e-03,  2.37463319e-01,  5.88612751e-04,
          4.34929243e-03,  1.60001529e-03,  4.34929243e-03,
          3.21371655e-02,  5.88612751e-04,  4.34929243e-03],
        [ 1.75242186e-07,  4.76300375e-07, -3.33332039e-01,
          3.51919722e-06,  9.56611258e-06,  2.60033327e-05,
          7.06843296e-05,  1.92139871e-04,  5.22290263e-04,
          1.41973208e-03,  3.85923184e-03,  1.04904797e-02,
          2.85160804e-02,  7.75147431e-02,  2.10706917e-01],
        [ 2.13451704e-01,  7.85244938e-02,  2.88875469e-02,
          1.06271346e-02, -3.31895107e-01,  1.31152593e-06,
          9.69072572e-06,  6.53287050e-08,  2.63420664e-05,
          1.31152593e-06,  2.63420664e-05,  1.31152593e-06,
          7.16051030e-05,  7.16051030e-05,  1.94642793e-04]]))